default_context:
  project_name: 'wool-hunter'
  project_slug: 'wool-hunter'
  domain_main: 'woolhunter.com'
  domain_staging: 'stag.woolhunter.com'
  docker_swarm_stack_name_main: 'woolhunter-com'
  docker_swarm_stack_name_staging: 'stag-woolhunter-com'
  secret_key: 'jiaQIAN520.'
  first_superuser: 'admin@woolhunter.com'
  first_superuser_password: 'jiaQIAN520.'
  backend_cors_origins: '["http://localhost", "http://localhost:4200", "http://localhost:3000", "http://localhost:8080", "https://localhost", "https://localhost:4200", "https://localhost:3000", "https://localhost:8080", "http://dev.woolhunter.com", "https://stag.woolhunter.com", "https://woolhunter.com", "http://local.dockertoolbox.tiangolo.com", "http://localhost.tiangolo.com"]'
  smtp_port: '587'
  smtp_host: ''
  smtp_user: ''
  smtp_password: ''
  smtp_emails_from_email: 'info@woolhunter.com'
  postgres_password: 'jiaQIAN520.'
  pgadmin_default_user: 'admin@woolhunter.com'
  pgadmin_default_user_password: 'jiaQIAN520.'
  traefik_constraint_tag: 'woolhunter.com'
  traefik_constraint_tag_staging: 'stag.woolhunter.com'
  traefik_public_constraint_tag: 'traefik-public'
  flower_auth: 'admin:jiaQIAN520.'
  sentry_dsn: ''
  docker_image_prefix: ''
  docker_image_backend: 'backend'
  docker_image_celeryworker: 'celeryworker'
  docker_image_frontend: 'frontend'
  _copy_without_render: [frontend/src/**/*.html, frontend/src/**/*.vue, frontend/node_modules/*, backend/app/app/email-templates/**]
  _template: ./
